### ISSUE TITLE
Error: Cannot find module 'gitlog'

### ISSUE THREAD

**Issue by allain** [captainsafia/dossier#2]
Tried it on both node 4 and 7 with the same effect.

```
npm install --global @captainsafia/dossier
dossier
```

yields:
```
module.js:472
    throw err;
    ^
Error: Cannot find module 'gitlog'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/allain/.nvm/versions/node/v7.5.0/lib/node_modules/@captainsafia/dossier/src/index.js:3:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by captainsafia** [comment]
Oops! Guess I shouldn't have rushed to publish this at 4am in the morning!

I just published a quick patch for this. Try it now?

**Comment by allain** [comment]
Great.

It's a neat tool.
